[project]
name = "sql2model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygments>=2.19.2",
    "pyinstaller>=6.15.0",
    "pyperclip>=1.9.0",
    "pyside6>=6.9.2",
    "sqlglot>=27.10.0",
]
